steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - VITE_API_BASE_URL=${_VITE_API_BASE_URL}
      - --build-arg
      - VITE_WS_BASE_URL=${_VITE_WS_BASE_URL}
      - -t
      - ${_IMAGE}
      - .

images:
  - ${_IMAGE}
