"""edit column

Revision ID: b9350e95910a
Revises: 9a1f7c0bd213
Create Date: 2026-05-12 05:15:28.823690

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b9350e95910a"
down_revision: Union[str, Sequence[str], None] = "9a1f7c0bd213"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chat_participant",
        "last_read_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.add_column("message", sa.Column("is_edited", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "is_edited")
    op.alter_column(
        "chat_participant",
        "last_read_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    # ### end Alembic commands ###
